// Placeholder for Firebase options generated by flutterfire configure.
// Replace this file by running: flutterfire configure
//
// See firebase_setup.md for instructions.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdFCbTWlOZTjEmXHyfyugIWAeut_SAvNw',
    appId: '1:998488215961:web:mock1234567890', // We use a mock web ID for testing
    messagingSenderId: '998488215961',
    projectId: 'bahikhata-b9521',
    authDomain: 'bahikhata-b9521.firebaseapp.com',
    storageBucket: 'bahikhata-b9521.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdFCbTWlOZTjEmXHyfyugIWAeut_SAvNw',
    appId: '1:998488215961:android:cb10553b1312614d0f0308',
    messagingSenderId: '998488215961',
    projectId: 'bahikhata-b9521',
    storageBucket: 'bahikhata-b9521.firebasestorage.app',
  );
}
